# Generated by Django 5.0.13 on 2025-03-18 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the article (up to 255 characters).', max_length=255)),
                ('body', models.TextField(help_text='The main content of the article')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the article was created. This field is set automatically.')),
                ('author', models.ForeignKey(help_text='The user who authored the article. Deleting the user will also delete their articles.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
